### ISSUE TITLE
Uncaught Assertion Error on Embed page

### ISSUE THREAD

**Issue by jpadilla** [charted-co/charted#101]
Noticed embed wasn't working for me. Tried digging a bit deeper and noticed that the error is reproduced on the embed page (eg: https://www.charted.co/embed/46e0cd2)

**Comment by valueof** [comment]
Yep, found the bug. Thanks for the report! I'll deploy the fixed version in a bit.

**Comment by valueof** [comment]
Your link works now.

**Comment by jpadilla** [comment]
@valueof confirmed, thanks!
